name: pull-request

on:
  pull_request:
    branches: [ main ]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to owner
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees: [context.repo.owner]
          });

  checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download
        git diff --exit-code go.mod go.sum

    - name: Run Linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        golangci-lint run ./...

    - name: Run Tests
      run: go test -v ./...
