name: pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to owner
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees: [context.repo.owner]
          });

  smoke-test:
    uses: ./.github/workflows/smoke-test.yaml
